Repository prgrms-web-devcourse/FEDC4-React-Study, pull requests merged in 2023-08, with the labels that each got.

#3 Init: react로 틱택토 게임 만들기 초기설정
  chaeyeon/tic-tac-toe/.gitignore
  chaeyeon/tic-tac-toe/README.md
  chaeyeon/tic-tac-toe/package-lock.json
  chaeyeon/tic-tac-toe/package.json
  chaeyeon/tic-tac-toe/public/index.html
  chaeyeon/tic-tac-toe/src/App.js
  chaeyeon/tic-tac-toe/src/index.js
  chaeyeon/tic-tac-toe/src/styles.css
Labels: FE

#6 [우창욱] Recoil을 사용한 간단한 상품 페이지 구현
  .gitignore
  wukdddang/01-recoil/.eslintrc.cjs
  wukdddang/01-recoil/.gitignore
  wukdddang/01-recoil/README.md
  wukdddang/01-recoil/index.html
  wukdddang/01-recoil/package-lock.json
  wukdddang/01-recoil/package.json
  wukdddang/01-recoil/public/vite.svg
  wukdddang/01-recoil/src/App.tsx
  wukdddang/01-recoil/src/components/CartItem.tsx
  wukdddang/01-recoil/src/components/Navbar.tsx
  wukdddang/01-recoil/src/components/ProductCard.tsx
  wukdddang/01-recoil/src/index.css
  wukdddang/01-recoil/src/interface/index.ts
  wukdddang/01-recoil/src/main.tsx
  wukdddang/01-recoil/src/model/dummyData.js
  wukdddang/01-recoil/src/pages/CartPage.tsx
  wukdddang/01-recoil/src/pages/DefaultPage.tsx
  wukdddang/01-recoil/src/pages/MainPage.tsx
  wukdddang/01-recoil/src/recoil/CartAtom.ts
  wukdddang/01-recoil/src/vite-env.d.ts
  wukdddang/01-recoil/tsconfig.json
  wukdddang/01-recoil/tsconfig.node.json
  wukdddang/01-recoil/vercel.json
  wukdddang/01-recoil/vite.config.ts
Labels: 리뷰 요청, 코칭 요청, FE

#4 [김다은] vite 초기설정
  kimdaeun/vite-project/.eslintrc.cjs
  kimdaeun/vite-project/.gitignore
  kimdaeun/vite-project/.storybook/main.ts
  kimdaeun/vite-project/.storybook/preview.ts
  kimdaeun/vite-project/README.md
  kimdaeun/vite-project/index.html
  kimdaeun/vite-project/package-lock.json
  kimdaeun/vite-project/package.json
  kimdaeun/vite-project/public/vite.svg
  kimdaeun/vite-project/src/App.tsx
  kimdaeun/vite-project/src/assets/react.svg
  kimdaeun/vite-project/src/components/Counter.tsx
  kimdaeun/vite-project/src/main.tsx
  kimdaeun/vite-project/src/stories/Counter.stories.ts
  kimdaeun/vite-project/src/vite-env.d.ts
  kimdaeun/vite-project/tsconfig.json
  kimdaeun/vite-project/tsconfig.node.json
  kimdaeun/vite-project/vite.config.ts
Labels: 리뷰 요청, 코칭 요청, FE, Ask

#7 [정동환] Docs: Next.js Concept - 2
  .gitignore
  donghwan/docs/next.js_concept.md
Labels: 리뷰 요청, FE, Docs

#11 [이채연] react로 틱택토 게임 만들기
  .gitignore
  chaeyeon/tic-tac-toe/src/App.js
  donghwan/docs/next.js_concept.md
Labels: 리뷰 요청, FE, Feat

#10 [김다은] posts api복습하기
  kimdaeun/vite-project/package-lock.json
  kimdaeun/vite-project/package.json
  kimdaeun/vite-project/src/App.jsx
  kimdaeun/vite-project/src/App.tsx
  kimdaeun/vite-project/src/components/Counter.tsx
  kimdaeun/vite-project/src/components/PostItem/index.jsx
  kimdaeun/vite-project/src/components/PostList/index.jsx
  kimdaeun/vite-project/src/components/PostProvider/index.jsx
  kimdaeun/vite-project/src/hooks/useAsync.js
  kimdaeun/vite-project/src/hooks/useAsyncFn.js
  kimdaeun/vite-project/src/main.tsx
  kimdaeun/vite-project/src/stories/Counter.stories.ts
Labels: 리뷰 요청, FE, Ask

#14 [김다은] posts api 삭제, 추가 기능 추가
  kimdaeun/vite-project/src/App.jsx
  kimdaeun/vite-project/src/components/PostAddForm/index.jsx
  kimdaeun/vite-project/src/components/PostItem/index.jsx
  kimdaeun/vite-project/src/components/PostList/index.jsx
  kimdaeun/vite-project/src/components/PostProvider/index.jsx
  kimdaeun/vite-project/src/hooks/useForm.tsx
Labels: 리뷰 요청, 코칭 요청, FE
